config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :areas

  get '/about' => 'pages#about'

  get '/chat' => 'pages#chat'

  root 'areas#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
	# scope :region, -> (region) { where region: region}
	# scope :zone, -> (zone) { where zone: zone}
	# scope :cost, -> (cost) { where cost: cost}
	# scope :green, -> (green) { where green: green}

	# scope :published, -> {where(:published => 1)}

	mount_uploader :image, ImageUploader

	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :areas
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
        if params[:category].blank?
          @areas = Area.where(nil).order("cost ASC") #creates an anonymous scope
          @areas = @areas.region(params[:region]) if params[:region].present?
          @areas = @areas.zone(params[:zone]) if params[:zone].present?
          @areas = @areas.cost(params[:cost]) if params[:cost].present?
          @areas = @areas.green(params[:green]) if params[:green].present?
        else
          @category_id = Category.find_by(name: params[:category]).id
          @areas = Area.where(category_id: @category_id).order("cost DESC")
          @areas = @areas.region(params[:region]) if params[:region].present?
          @areas = @areas.zone(params[:zone]) if params[:zone].present?
          @areas = @areas.cost(params[:cost]) if params[:cost].present?
          @areas = @areas.green(params[:green]) if params[:green].present?
        end

       
     # else
     #   @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :region, :zone, :cost, :description, :transport, :nightlife, :food, :green, :image, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :crime)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def chat
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area, :html => { multipart: true }) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt:"Choose a category"}, {class:"btn btn-default dropdown-toggle"} %>
  </div>


  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :zone %><br>
    <%= f.number_field :zone, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :transport %><br>
    <%= f.number_field :transport, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :nightlife %><br>
    <%= f.number_field :nightlife, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :food %><br>
    <%= f.number_field :food, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :green %><br>
    <%= f.number_field :green, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.number_field :published, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<div class="container">
	<h1>Editing Area</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @area %> |
	<%= link_to 'Back', areas_path %>
</div>

app/views/areas/index.html.erb
<div class="container" style="padding-top:20px;">
  <div class="filters">
      <div class="row">
            <div class="col-sm-4">
              <div class="btn-group btn-group-lg filter-button-group" data-filter-group="zone" role="group" data-toggle="tooltip" data-placement="bottom" title="How far do you want to travel?">
                <button class="btn btn-filter button" data-filter="">All Zones</button>
                <button class="btn btn-filter button" data-filter=".zoneone">Zone 1</button>
                <button class="btn btn-filter button" data-filter=".zonetwo">Zone 2</button>
                <button class="btn btn-filter button" data-filter=".zonethree">Zone 3</button>
              </div>
            </div>
    
            <div class="col-sm-4">
              <div class="btn-group btn-group-lg filter-button-group" data-filter-group="region" role="group" data-toggle="tooltip" data-placement="bottom" title="Where in London do you want to live?">
                <button class="btn btn-filter button" data-filter=".north" style="display:inline;">North</button>
                <button class="btn btn-filter button" data-filter=".south" style="display:inline;">South</button>
                <button class="btn btn-filter button" data-filter=".east" style="display:inline;">East</button>
                <button class="btn btn-filter button" data-filter=".west" style="display:inline;">West</button>
              </div>
            </div>

            <div class="col-sm-4">
              <div class="btn-group btn-group-lg filter-button-group" data-filter-group="cost" role="group" data-toggle="tooltip" data-placement="bottom" title="How much do you want to pay?">
                <button class="btn btn-filter button" data-filter="" style="display:inline;">All £</button>
                <button class="btn btn-filter button" data-filter=".cheap" style="display:inline;">£</button>
                <button class="btn btn-filter button" data-filter=".affordable" style="display:inline;">£££</button>
                <button class="btn btn-filter button" data-filter=".expensive" style="display:inline;">£££££</button>
              </div>
            </div>
      </div>

      <div class="row">
        <div class="col-sm-4">
              <div class="btn-group btn-group-lg filter-button-group" data-filter-group="type" role="group" aria-label="Basic example">
                <button class="btn btn-filter button" data-filter="" style="display:inline;">All</button>
                <button class="btn btn-filter button" data-filter=".safe" style="display:inline;">Safe<span class="filter-count hidden-xs"></span></button>
                <button class="btn btn-filter button" data-filter=".nightlife" style="display:inline;">dance<span class="filter-count hidden-xs"></span></button>
                <button class="btn btn-filter button" data-filter=".green" style="display:inline;">eat<span class="filter-count hidden-xs"></span></button> 
              </div>
        </div>
<!--         <div class="col-sm-6">
              <div class="btn-group btn-group-lg filter-button-group" data-filter-group="type" role="group" aria-label="Basic example">
                <button class="btn btn-filter button" data-filter="" style="display:inline;">All</button>
                <button class="btn btn-filter button" data-filter=".safe" style="display:inline;">Safe</button>
                <button class="btn btn-filter button" data-filter=".nightlife" style="display:inline;">Night</button>
                <button class="btn btn-filter button" data-filter=".green" style="display:inline;">Food</button> 
              </div>
        </div> -->
      </div>
  </br>
  </div>
      </br>
      </br>
      <div class="row grid">
          
          <% @areas.each do |area| %>
              <div class="col-md-4 col-xs-6 grid-item <%= area.cost < 750 ? 'cheap' : '' %> <%= area.cost >750 ? 'affordable' : '' %> <%= area.cost > 900 ? 'expensive' : '' %> <%= area.green >= 7 ? 'green' : '' %> <%= area.nightlife >= 7 ? 'nightlife' : '' %> <%= area.zone === 1 ? 'zoneone' : '' %> <%= area.zone === 2 ? 'zonetwo' : '' %> <%= area.zone === 3 ? 'zonethree' : '' %> <%= area.category.crime >= 7 ? 'safe' : '' %> <%= area.region === 'North' ? 'north' : '' %> <%= area.region === 'South' ? 'south' : '' %> <%= area.region === 'East' ? 'east' : '' %> <%= area.region === 'West' ? 'west' : '' %>">
                    <%= link_to area do %>
                    <div class="area-tile" id="diva_id" style="background: linear-gradient(rgba(0, 0, 0, 0.55), rgba(0, 0, 0, 0.55)),rgba(0,0,0,0.55) url('<%= area.image.url %>') no-repeat center;background-size:cover;">
                      <div class="area-inside">
                          <div class="attr top-left">Zone <%= area.zone %></div>
                          <div class="attr top-right">£<%= area.cost %> / m</div>
                          <div class="attr bottom-left"><%= area.region %></div>
                          <div class="attr bottom-right">14 mins</div>
                          <div class="attr area-title"><span class="title"><%= area.name %></span></br><span class="sub-title"><%= area.category.name %></span></div>
                      </div>
                    </div>
                    <% end %>
                </div>              
          <% end %>
      </div>

    <% if current_user.try(:admin?) %>
        <%= link_to 'New Area', new_area_path %>
    <% else %>
    <% end %>
</div>


  
<script type="text/javascript">

$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})

// init Isotope
var $grid = $('.grid').isotope({
  itemSelector: '.grid-item'
});

// store filter for each group
var filters = {};

var $filterButtons = $('.filters .btn');

updateFilterCounts();

$('.filters').on( 'click', '.button', function() {
  var $this = $(this);
  // get group key
  var $buttonGroup = $this.parents('.btn-group');
  var filterGroup = $buttonGroup.attr('data-filter-group');
  // set filter for group
  filters[ filterGroup ] = $this.attr('data-filter');
  // combine filters
  var filterValue = concatValues( filters );
  // set filter for Isotope
  $grid.isotope({ filter: filterValue });
  // console.log(filterValue);
  updateFilterCounts();
  console.log( filters );
});

$('.btn-group').each( function( i, buttonGroup ) {
  var $buttonGroup = $( buttonGroup );
  $buttonGroup.on( 'click', 'button', function() {
    $buttonGroup.find('.is-checked').removeClass('is-checked');
    $( this ).addClass('is-checked');
  });
});

function updateFilterCounts()  {
  // get filtered item elements
  var itemElems = $grid.isotope('getFilteredItemElements');
  var $itemElems = $( itemElems );
  $filterButtons.each( function( i, button ) {
    var $button = $( button );
    var filterValue = $button.attr('data-filter');
    if ( !filterValue ) {
      // do not update 'any' buttons
      return;
    }
    var count = $itemElems.filter( filterValue ).length;
    $button.find('.filter-count').text( count );
  });
}

// flatten object by concatting values
function concatValues( obj ) {
  var value = '';
  for ( var prop in obj ) {
    value += obj[ prop ];
  }
  return value;
}

</script>

app/views/areas/new.html.erb
<div class="container">
	<h1>New Area</h1>

	<%= render 'form' %>

	<%= link_to 'Back', areas_path %>

</div>

app/views/areas/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron img-overlay" style="background: linear-gradient(rgba(0, 0, 0, 0.55), rgba(0, 0, 0, 0.55)),rgba(0,0,0,0.55) url('<%= @area.image.url %>') no-repeat center;background-position:0;background-size:cover;">
  <div class="container" style="text-align:center;height:30vh">

    <div class="row" style="color:#FFF;">
      <div class="col-sm-12">
       <h1><%= @area.name %></h1>
       <p><%= @area.category.name %></p>
     </br>
     <button class="btn btn-joinchat" href="/chat.html">Join Chat</button>
   </div>
 </div>
</div>
</div>


<div class="container" style="padding-bottom:50px;">
  <div class="row">
    <div class="col-md-8 col-sm-6">
      <p><%= @area.description %></p>
      <table class="table table-responsive" style="width:100%;">
        <tr>
          <td class="col-md-4" style="font-weight:bold">Local rent amount:</td>
          <td class="col-md-2" style="text-align:right;">£<%= @area.cost %> / m</td>
        </tr>
        <tr>
          <td class="col-md-4" style="font-weight:bold">TfL Zone:</td>
          <td class="col-md-2" style="text-align:right;"><%= @area.zone %></td> 
        </tr>
        <tr>
          <td class="col-md-4" style="font-weight:bold">Travel Time:</td>
          <td class="col-md-2" style="text-align:right;">14 mins</td> 
        </tr>
      </table>
    </div>
    
    <div class="col-md-4 col-sm-6 ratings">

      <label for="progress-bar">Transport</label> <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="Time to city centre, transport options"></span>
      <div class="progress">
        <div class="progress-bar" id="rating" role="progressbar" aria-valuenow="<%= @area.transport %>" aria-valuemin="0" aria-valuemax="10" style="width:<%= @area.transport %>0%;">
          <%= @area.transport %>
        </div>
      </div>

      <label for="progress-bar">Nightlife <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="Quality of nightlife, different scenes and number of venues"></span></label>
      <div class="progress">
        <div class="progress-bar" id="rating" role="progressbar" aria-valuenow="<%= @area.nightlife %>" aria-valuemin="0" aria-valuemax="10" style="width:<%= @area.nightlife %>0%;">
          <%= @area.nightlife %>
        </div>
      </div>

      <label for="progress-bar">Food & Drink <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="Tooltip on right"></span></label>
      <div class="progress">
        <div class="progress-bar" id="rating" role="progressbar" aria-valuenow="<%= @area.food %>" aria-valuemin="0" aria-valuemax="10" style="width:<%= @area.food %>0%;">
          <%= @area.food %>
        </div>
      </div>
      <label for="progress-bar">Green Spaces <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="Tooltip on right"></span></label>
      <div class="progress">
        <div class="progress-bar" id="rating" role="progressbar" aria-valuenow="<%= @area.green %>" aria-valuemin="0" aria-valuemax="10" style="width:<%= @area.green %>0%;">
          <%= @area.green %>
        </div>
      </div>
      <label for="progress-bar">Crime/Safety <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="Rating based on crime stats for <%= @area.category.name %> borough"></span></label>
      <div class="progress">
        <div class="progress-bar" id="rating" role="progressbar" aria-valuenow="<%= @area.category.crime %>" aria-valuemin="0" aria-valuemax="10" style="width:<%= @area.category.crime %>0%;">
          <%= @area.category.crime %>
        </div>
      </div>
      <a href="#">How are these ratings calculated?</a>

      <% if current_user.try(:admin?) %>
      <%= link_to 'Edit', edit_area_path %>
      <% else %>
      
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">

$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})

$(" #rating[aria-valuenow]").each(function() {
  if ($(this).attr('aria-valuenow') >= 7) {
            $(this).addClass('good'); // Or whatever
          }
        });

$(" #rating[aria-valuenow]").each(function() {
  if ($(this).attr('aria-valuenow') <=3) {
            $(this).addClass('bad'); // Or whatever
          }
        });

$(" #rating[aria-valuenow]").each(function() {
  if ($(this).attr('aria-valuenow') >3) {
            $(this).addClass('average'); // Or whatever
          }
        });


</script>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :crime %><br>
    <%= f.text_field :crime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <p id="notice"><%= notice %></p>

    <h1>Listing Categories</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Crime</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= category.crime %></td>
          <td><%= link_to 'Show', category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Category', new_category_path %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<p>
  <strong>Crime:</strong>
  <%= @category.crime %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_bootstrap.html.erb
 <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  
  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

app/views/layouts/_footer.html.erb

      <footer class="footer navbar-fixed-bottom" style="margin-top:50px !important">
      <div class="container-fluid">
        <p style="text-align:right;padding:0 !important">
            <a href="https://twitter.com/TwitterDev" class="twitter-follow-button" data-size="large" data-show-count="false">Follow @LondonLiving</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        </p>
      </div>
    </footer>
    </div> <!-- /container -->        

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-85132636-1', 'auto');
      ga('send', 'pageview');

    </script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to root_path do %>
             <%= image_tag "big-ben.svg", class: "navbar-brand" %>
          <% end %>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              <!-- <li><a href="/about.html">About</a></li> -->
              <li><a href="/chat.html">Community</a></li>
              <% if user_signed_in? %>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <!-- <li><%= link_to "Sign in", new_user_session_path %></li> -->
              <% end %>
            </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LondonList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="apple-touch-icon" href="apple-touch-icon.png">
  <%= render 'layouts/bootstrap' %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
</head>

<body>

<%= render 'layouts/navbar' %>
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->

<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<h1>We would love to hear from you!</h1>
<p>Contact us at alex@baserails.com</p>
<p>Copyright Alex Yang</p>

app/views/pages/chat.html.erb
<div class="jumbotron" style="background-color:#FF4742;color:#FFF;text-align:center">
      <div class="container">
          <div class="col-md-8 col-md-offset-2">
              <h3 style="font-weight:bold;">Join #londonliving, a chat group for those moving to, living in, or interested in London</h3></br>
              <p style="font-size:1em">As a member of London List, you get access to  #london, a chat group on Slack, which lets you connect with fellow Londoners, exhange information about your area and stay informed about what's going on in town.</p>
              <p style="font-size:1em">Our Slack community is in beta, use the sign up button below to get your name on the list. Invites are vetted and accepted within 1 hour (unless of course, you're a robot).</p></br>
              <button class="btn" style="background:transparent;color:#FFF;font-weight:bold;border:2px solid #FFF">Sign up now</button>
          </div>
      </div>
   </div>

   <div class="container" style="text-align:center">
      <div class="row">
          <h3 style="font-weight:bold;">Ask questions, get answers</h3>
          <div class="row" style="font-weight:bold;text-align:left">
              <div class="col-md-16 col-md-offset-3">
                <img src="https://randomuser.me/api/portraits/men/20.jpg" style="border-radius:999px;height:42px;">
                <p>Looking for month rental in Shoreditch. Less than £500 all in</p>
                                <img src="https://randomuser.me/api/portraits/women/65.jpg" style="border-radius:999px;height:42px;">
                <p>Is London a safe place to live? What areas should I avoid?</p>
                                <img src="https://randomuser.me/api/portraits/men/66.jpg" style="border-radius:999px;height:42px;">
                <p>Travel time from Putney seems good, but I've heard bad things about the district line, anyone?</p>
              </div>
          </div>

      </div>
   </div>